# Generated by Django 5.1.1 on 2024-09-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Jhapa', 'Jhapa'), ('Ilam', 'Ilam'), ('Biratnagar', 'Biratnagar')], max_length=100)),
            ],
        ),
    ]
