# Generated by Django 5.0.3 on 2024-09-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('city', models.CharField(choices=[('New York', 'New York'), ('Los Angeles', 'Los Angeles'), ('Chicago', 'Chicago')], default='New York', max_length=20)),
                ('password', models.CharField(max_length=8)),
                ('lisense_num', models.PositiveIntegerField()),
            ],
        ),
    ]
