# Generated by Django 5.0.3 on 2024-09-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(max_length=280),
        ),
    ]
