# Generated by Django 5.0.3 on 2024-09-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_driver_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='auto_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
